# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "robosu12"
repo_name: "daily_paper_update"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LiDAR SLAM": 
        filters: ["SLAM", "LiDAR", "LiDAR-inertial", "Odometry", "sensor Fusion", "Localization", "Mapping"]
    "Visual SLAM":
        filters: ["Visual Odometry", "Visual SLAM", ]
    "Loop Closure":
        filters: ["Place recognition", "Relocalization", "Global Localization", "Loop Closure"]
    "Keypoint Detection":
        filters: ["Keypoint Detection", "Feature Descriptor"]
    "Image Matching":
        filters: ["Image Matching", "Keypoint Matching", "Local Feature Matching"]
    "3DGS":
        filters: ["3DGS"]
